name: Test
on:
  push:
jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install -r requirements.txt
    - run: python main.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
